STATES = {
    'AL': {'STFIPS': '01', 'Districts': {'congress20': 7, 'congress10': 7, 'state_senate': 35, 'state_house': 105}},
    'AK': {'STFIPS': '02', 'Districts': {'state_senate': 20, 'state_house': 40}},
    'AZ': {'STFIPS': '04', 'Districts': {'congress20': 9, 'congress10': 9, 'state_senate': 30}}, # multi-member house elected from each senate district
    'AR': {'STFIPS': '05', 'Districts': {'congress20': 4, 'congress10': 4, 'state_senate': 35, 'state_house': 100}},
    'CA': {'STFIPS': '06', 'Districts': {'congress20': 52, 'congress10': 53, 'state_senate': 40, 'state_house': 80}},
    'CO': {'STFIPS': '08', 'Districts': {'congress20': 8, 'congress10': 7, 'state_senate': 35, 'state_house': 65}},
    'CT': {'STFIPS': '09', 'Districts': {'congress20': 5, 'congress10': 5, 'state_senate': 36, 'state_house': 151}},
    'DE': {'STFIPS': '10', 'Districts': {'state_senate': 21, 'state_house': 41}},
    'DC': {'STFIPS': '11', 'Districts': {'wards': 8}},
    'FL': {'STFIPS': '12', 'Districts': {'congress20': 28, 'congress10': 27, 'state_senate': 40, 'state_house': 120}},
    'GA': {'STFIPS': '13', 'Districts': {'congress20': 14, 'congress10': 14, 'state_senate': 56, 'state_house': 180}},
    'HI': {'STFIPS': '15', 'Districts': {'congress20': 2, 'congress10': 2, 'state_senate': 25, 'state_house': 51}},
    'ID': {'STFIPS': '16', 'Districts': {'congress20': 2, 'congress10': 2, 'state_senate': 35}}, # multi-member house elected from each senate district
    'IL': {'STFIPS': '17', 'Districts': {'congress20': 17, 'congress10': 18, 'state_senate': 59, 'state_house': 118}},
    'IN': {'STFIPS': '18', 'Districts': {'congress20': 9, 'congress10': 9, 'state_senate': 50, 'state_house': 100}},
    'IA': {'STFIPS': '19', 'Districts': {'congress20': 4, 'congress10': 4, 'state_senate': 50, 'state_house': 100}},
    'KS': {'STFIPS': '20', 'Districts': {'congress20': 4, 'congress10': 4, 'state_senate': 40, 'state_house': 125}},
    'KY': {'STFIPS': '21', 'Districts': {'congress20': 6, 'congress10': 6, 'state_senate': 38, 'state_house': 100}},
    'LA': {'STFIPS': '22', 'Districts': {'congress20': 6, 'congress10': 6, 'state_senate': 39, 'state_house': 105}},
    'ME': {'STFIPS': '23', 'Districts': {'congress20': 2, 'congress10': 2, 'state_senate': 35, 'state_house': 151}},
    'MD': {'STFIPS': '24', 'Districts': {'congress20': 8, 'congress10': 8, 'state_senate': 47}}, # multi-member house
    'MA': {'STFIPS': '25', 'Districts': {'congress20': 9, 'congress10': 9, 'state_senate': 40, 'state_house': 160}},
    'MI': {'STFIPS': '26', 'Districts': {'congress20': 13, 'congress10': 14, 'state_senate': 1, 'state_house': 1}},
    'MN': {'STFIPS': '27', 'Districts': {'congress20': 8, 'congress10': 8, 'state_senate': 1, 'state_house': 1}},
    'MS': {'STFIPS': '28', 'Districts': {'congress20': 4, 'congress10': 4, 'state_senate': 1, 'state_house': 1}},
    'MO': {'STFIPS': '29', 'Districts': {'congress20': 8, 'congress10': 8, 'state_senate': 1, 'state_house': 1}},
    'MT': {'STFIPS': '30', 'Districts': {'congress20': 2,'state_senate': 1, 'state_house': 1}},
    'NE': {'STFIPS': '31', 'Districts': {'congress20': 3, 'congress10': 3, 'state_senate': 1, 'state_house': 1}},
    'NV': {'STFIPS': '32', 'Districts': {'congress20': 4, 'congress10': 4, 'state_senate': 1, 'state_house': 1}},
    'NH': {'STFIPS': '33', 'Districts': {'congress20': 2, 'congress10': 2, 'state_senate': 1, 'state_house': 1}},
    'NJ': {'STFIPS': '34', 'Districts': {'congress20': 12, 'congress10': 12, 'state_senate': 1, 'state_house': 1}},
    'NM': {'STFIPS': '35', 'Districts': {'congress20': 3, 'congress10': 3, 'state_senate': 1, 'state_house': 1}},
    'NY': {'STFIPS': '36', 'Districts': {'congress20': 26, 'congress10': 27, 'state_senate': 1, 'state_house': 1}},
    'NC': {'STFIPS': '37', 'Districts': {'congress20': 14, 'congress10': 13, 'state_senate': 1, 'state_house': 1}},
    'ND': {'STFIPS': '38', 'Districts': {'state_senate': 1, 'state_house': 1}},
    'OH': {'STFIPS': '39', 'Districts': {'congress20': 15, 'congress10': 16, 'state_senate': 1, 'state_house': 1}},
    'OK': {'STFIPS': '40', 'Districts': {'congress20': 5, 'congress10': 5, 'state_senate': 1, 'state_house': 1}},
    'OR': {'STFIPS': '41', 'Districts': {'congress20': 6, 'congress10': 5, 'state_senate': 1, 'state_house': 1}},
    'PA': {'STFIPS': '42', 'Districts': {'congress20': 17, 'congress10': 18, 'state_senate': 1, 'state_house': 1}},
    'PR': {'STFIPS': '72', 'Districts': {'state_senate': 8, 'state_house': 40}},
    'RI': {'STFIPS': '44', 'Districts': {'congress20': 2, 'congress10': 2, 'state_senate': 1, 'state_house': 1}},
    'SC': {'STFIPS': '45', 'Districts': {'congress20': 7, 'congress10': 7, 'state_senate': 1, 'state_house': 1}},
    'SD': {'STFIPS': '46', 'Districts': {'state_senate': 1, 'state_house': 1}},
    'TN': {'STFIPS': '47', 'Districts': {'congress20': 9, 'congress10': 9, 'state_senate': 1, 'state_house': 1}},
    'TX': {'STFIPS': '48', 'Districts': {'congress20': 38, 'congress10': 36, 'state_senate': 1, 'state_house': 1}},
    'UT': {'STFIPS': '49', 'Districts': {'congress20': 4, 'congress10': 4, 'state_senate': 1, 'state_house': 1}},
    'VT': {'STFIPS': '50', 'Districts': {'state_senate': 1, 'state_house': 1}},
    'VA': {'STFIPS': '51', 'Districts': {'congress20': 11, 'congress10': 11, 'state_senate': 1, 'state_house': 1}},
    'WA': {'STFIPS': '53', 'Districts': {'congress20': 10, 'congress10': 10, 'state_senate': 1, 'state_house': 1}},
    'WV': {'STFIPS': '54', 'Districts': {'congress20': 2, 'congress10': 3, 'state_senate': 1, 'state_house': 1}},
    'WI': {'STFIPS': '55', 'Districts': {'congress20': 8, 'congress10': 8, 'state_senate': 1, 'state_house': 1}},
    'WY': {'STFIPS': '56', 'Districts': {'state_senate': 1, 'state_house': 1}}}